#!/usr/bin/python3
import time

import Adafruit_GPIO as GPIO
import Adafruit_GPIO.MCP230xx as MCP230xx

mcp = MCP230xx.MCP23017()  # This assumes the MCP23017 is at the default address 0x20, if not pass in an argument with the actual address in hex.

# Setup pin 1 as an output and pin 2 as an input, very similar to RPi.GPIO library.
mcp.setup(0, GPIO.OUT)
mcp.setup(1, GPIO.OUT)
mcp.setup(2, GPIO.OUT)
mcp.setup(3, GPIO.OUT)
mcp.setup(4, GPIO.OUT)
mcp.setup(5, GPIO.OUT)
mcp.setup(6, GPIO.OUT)
mcp.setup(7, GPIO.OUT)
mcp.setup(8, GPIO.OUT)
mcp.setup(9, GPIO.OUT)
mcp.setup(10, GPIO.OUT)
mcp.setup(11, GPIO.OUT)
mcp.setup(12, GPIO.OUT)
mcp.setup(13, GPIO.OUT)
mcp.setup(14, GPIO.OUT)
mcp.setup(15, GPIO.OUT)

# Loop forever blinking pin 1 high and low every second.
while True:
    mcp.output(0, GPIO.HIGH)
    time.sleep(1.0)
    mcp.output(1, GPIO.HIGH)
    time.sleep(1.0)
    mcp.output(2, GPIO.HIGH)
    time.sleep(1.0)
    mcp.output(3, GPIO.HIGH)
    time.sleep(1.0)
    mcp.output(4, GPIO.HIGH)
    time.sleep(1.0)
    mcp.output(5, GPIO.HIGH)
    time.sleep(1.0)
    mcp.output(6, GPIO.HIGH)
    time.sleep(1.0)
    mcp.output(7, GPIO.HIGH)
    time.sleep(1.0)
    mcp.output(8, GPIO.HIGH)
    time.sleep(1.0)
    mcp.output(9, GPIO.HIGH)
    time.sleep(1.0)
    mcp.output(10, GPIO.HIGH)
    time.sleep(1.0)
    mcp.output(11, GPIO.HIGH)
    time.sleep(1.0)
    mcp.output(12, GPIO.HIGH)
    time.sleep(1.0)
    mcp.output(13, GPIO.HIGH)
    time.sleep(1.0)
    mcp.output(14, GPIO.HIGH)
    time.sleep(1.0)
    mcp.output(15, GPIO.HIGH)
    time.sleep(5.0)
    mcp.output(15, GPIO.LOW)
    time.sleep(1.0)
    mcp.output(14, GPIO.LOW)
    time.sleep(1.0)
    mcp.output(13, GPIO.LOW)
    time.sleep(1.0)
    mcp.output(12, GPIO.LOW)
    time.sleep(1.0)
    mcp.output(11, GPIO.LOW)
    time.sleep(1.0)
    mcp.output(10, GPIO.LOW)
    time.sleep(1.0)
    mcp.output(9, GPIO.LOW)
    time.sleep(1.0)
    mcp.output(8, GPIO.LOW)
    time.sleep(1.0)
    mcp.output(7, GPIO.LOW)
    time.sleep(1.0)
    mcp.output(6, GPIO.LOW)
    time.sleep(1.0)
    mcp.output(5, GPIO.LOW)
    time.sleep(1.0)
    mcp.output(4, GPIO.LOW)
    time.sleep(1.0)
    mcp.output(3, GPIO.LOW)
    time.sleep(1.0)
    mcp.output(2, GPIO.LOW)
    time.sleep(1.0)
    mcp.output(1, GPIO.LOW)
    time.sleep(1.0)
    mcp.output(0, GPIO.LOW)
    time.sleep(5.0)

